GET https://jsonplaceholder.typicode.com/todos

###

GET https://jsonplaceholder.typicode.com/todos/10

###

GET https://jsonplaceholder.typicode.com/albums?userId=2

###

GET https://jsonplaceholder.typicode.com/comments

###

GET https://swapi.dev/api/films

###
GET https://swapi.dev/api/vehicles

###

GET https://swapi.dev/api/vehicles?page=2

###

GET https://swapi.dev/api/planets?results?